name: Hello Github Action


on:
  push:

jobs:
  gret:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout Repository
          uses: action/checkout@v4

        - name: Print Hello
          run: echo "Hello from github Action!"

        - name: Print Date
          run: date

        - name: Print Branch name
          run: echo "Branch: ${{ github.ref_name }}"

        - name: List files
          run: ls -la

        - name: Print Runner OS
          run: echo "Runner OS: $RUNNER_OS"

